#!/bin/sh
# Builds fft.c -> fft.wasm -> fft_wasm.js (base64-embedded, so the page works
# from file:// with no server and no wasm fetch).
# Requires zig (https://ziglang.org/download/ — portable zip is fine):
#   ZIG=/path/to/zig ./build.sh
set -e
cd "$(dirname "$0")"
ZIG="${ZIG:-zig}"

"$ZIG" cc -target wasm32-freestanding -O3 -msimd128 -fno-builtin -nostdlib \
  -Wl,--no-entry -Wl,--export-memory fft.c -o fft.wasm

printf '// generated by build.sh — do not edit\nconst WASM_B64 = "%s";\n' \
  "$(base64 -w0 fft.wasm)" > fft_wasm.js

echo "built fft.wasm ($(wc -c < fft.wasm) bytes) and fft_wasm.js"
